### ISSUE TITLE
Errors when no access/secret key are provided

### ISSUE THREAD

**Issue by rajasaur** [gercograndia/aws-iam-tester#1]
Hi, Thanks a lot for this tool, I was going crazy trying to simulate the policy simulator using aws cli when I stumbled on this project.

I think it will help to provide a meaningful message if we run this without providing the access/secret key. Currently we get this.
```
ERROR:	An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
Traceback (most recent call last):
  File "/Users/raja/projects/virtualenvs/iam-tester/lib/python3.7/site-packages/aws_iam_tester/cli.py", line 151, in main
    account_id = sts_client.get_caller_identity()["Account"]
  File "/Users/raja/projects/virtualenvs/iam-tester/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/raja/projects/virtualenvs/iam-tester/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
```

Also, it will help to indicate what is the minimum role required to be able to run this, it looks like if the user doesnt have iam:ListAccountAliases then this tool doesnt work. It will help to provide a help message accordingly to setup (Either in the tool or in the README) so that new users will find it beneficial.

I can try and provide a PR if you are okay with that.

**Comment by gercograndia** [comment]
Hi Raja,

Glad you like it :-)

Please go ahead with the PR, both are good suggestions.

Regards,
Gerco

**Comment by gercograndia** [comment]
Have incorporated some changes in this regards, have a look whether that helps you. I'll close the case for now.
