### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by sdemjanenko** [gercograndia/aws-iam-tester#2]
When I try running `action -u <user> -a 'glue:DeleteTable'` I get
```
Exception occured: echo() got an unexpected keyword argument 'bold'
```

I used pipenv to install this module. From what I can tell, the error is coming from `click`. The version that I have installed is:
```
        "click": {
            "hashes": [
                "sha256:d2b5255c7c6349bc1bd1e59e08cd12acbbd63ce649f2588755783aa94dfb6b1a",
                "sha256:dacca89f4bfadd5de3d7489b7c8a566eee0d3676333fbb50030263894c38c0dc"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "version": "==7.1.2"
        },
```

**Comment by gercograndia** [comment]
Hi,

Sorry, just a bug, literally one 's' was missing.

Anyways, updated version published.

Cheers!

**Comment by sdemjanenko** [comment]
Thats good to hear. I'm not super familiar with `click`. Looking at the `click` source makes me think the the correct fix is:
```diff
-click.echo(f"Test:", bold=True)
+click.echo(click.style(f'Test:', bold=True))
```

**Comment by gercograndia** [comment]
That indeed would be one way to solve it.

Easier is (and that is how it is done now) to change it from:
`click.echo(f"Test:", bold=True)`

to:
`click.secho(f"Test:", bold=True)`

A git reset I had to do was the reason this issue crept in. But anyways, it should be solved now. Please test it and close this issue if it works for you.

**Comment by sdemjanenko** [comment]
I've confirmed that this is fixed on my end. Thanks the the super fast response!
