### ISSUE TITLE
Include/Exclude my organization's service control policies (SCPs)? 

### ISSUE THREAD

**Issue by druffing2** [gercograndia/aws-iam-tester#6]
In the AWS policy simulator, simulations will only properly simulate when I uncheck 'AWS Organizations SCPs' when in my organization's development account. Is there an option to disable SCPs when running the aws-iam-tester?

**Comment by gercograndia** [comment]
no, at the moment there isn't. Quickly checked the boto3 documentation but can't find anything that looks like it. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.simulate_principal_policy
